[2021-07-18 16:29:34,343] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: treino-01.Hello_Bash 2021-07-18T19:04:00+00:00 [queued]>
[2021-07-18 16:29:34,349] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: treino-01.Hello_Bash 2021-07-18T19:04:00+00:00 [queued]>
[2021-07-18 16:29:34,350] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 16:29:34,353] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2021-07-18 16:29:34,353] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 16:29:34,371] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): Hello_Bash> on 2021-07-18T19:04:00+00:00
[2021-07-18 16:29:34,374] {standard_task_runner.py:52} INFO - Started process 14648 to run task
[2021-07-18 16:29:34,378] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'treino-01', 'Hello_Bash', '2021-07-18T19:04:00+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/treino01.py', '--cfg-path', '/tmp/tmpwehh7uxa', '--error-file', '/tmp/tmpny0iieqb']
[2021-07-18 16:29:34,378] {standard_task_runner.py:77} INFO - Job 6: Subtask Hello_Bash
[2021-07-18 16:29:34,427] {logging_mixin.py:104} INFO - Running <TaskInstance: treino-01.Hello_Bash 2021-07-18T19:04:00+00:00 [running]> on host julio-VirtualBox
[2021-07-18 16:29:34,487] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=julio.zeferino@bex-team.com,julioszeferino@outlook.com.br
AIRFLOW_CTX_DAG_OWNER=Neylson - IGTI
AIRFLOW_CTX_DAG_ID=treino-01
AIRFLOW_CTX_TASK_ID=Hello_Bash
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T19:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-18T19:04:00+00:00
[2021-07-18 16:29:34,488] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-18 16:29:34,488] {subprocess.py:63} INFO - Running command: ['bash', '-c', '\n    echo "Hello Airflow from Bash!\n    ']
[2021-07-18 16:29:34,495] {subprocess.py:74} INFO - Output:
[2021-07-18 16:29:34,496] {subprocess.py:78} INFO - bash: -c: line 1: unexpected EOF while looking for matching `"'
[2021-07-18 16:29:34,497] {subprocess.py:78} INFO - bash: -c: line 3: syntax error: unexpected end of file
[2021-07-18 16:29:34,497] {subprocess.py:82} INFO - Command exited with return code 1
[2021-07-18 16:29:34,503] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/julio/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/julio/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/julio/anaconda3/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/julio/anaconda3/lib/python3.8/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-18 16:29:34,508] {taskinstance.py:1544} INFO - Marking task as UP_FOR_RETRY. dag_id=treino-01, task_id=Hello_Bash, execution_date=20210718T190400, start_date=20210718T192934, end_date=20210718T192934
[2021-07-18 16:29:34,538] {local_task_job.py:149} INFO - Task exited with return code 1
